#include "nsISupports.idl"
#include "nsIDOMWindow.idl"
#include "gmIMenuCommand.idl"

[scriptable, uuid(937ccbf0-1cc7-11da-8cd6-0800200c9a66)]
interface gmIBrowserWindow : nsISupports
{
  void registerMenuCommand(in gmIMenuCommand menuCommand);
  void openInTab(in nsIDOMWindow window, in AString url);
};
