pref("extensions.{e4a8a97b-f2ed-450b-b12d-ee082ba24781}.description", "chrome://greasemonkey/locale/greasemonkey.properties");
pref("extensions.greasemonkey.dataIsGreaseable", false);
pref("extensions.greasemonkey.enableScriptRefreshing", true);
pref("extensions.greasemonkey.fileIsGreaseable", false);
pref("extensions.greasemonkey.globalExcludes", '[]');
pref("extensions.greasemonkey.newScript.removeUnused", true);
pref("extensions.greasemonkey.newScript.template", '// ==UserScript==\n// @name        %name%\n// @namespace   %namespace%\n// @description %description%\n// @include     %include%\n// @exclude     %exclude%\n// @version     1\n// @grant       none\n// ==/UserScript==');
pref("extensions.greasemonkey.haveInsertedToolbarbutton", false);
pref("extensions.greasemonkey.installDelay", 5);
pref("extensions.greasemonkey.logChrome", false);
pref("extensions.greasemonkey.requireSecureUpdates", true);
pref("extensions.greasemonkey.showGrantsWarning", true);
pref("extensions.greasemonkey.sniffGrants", false);
pref("extensions.greasemonkey.sortBy", "uiState,name");
pref("extensions.greasemonkey.stats.id", "");
pref("extensions.greasemonkey.stats.interval", 604800000);  // ms = 1 week
pref("extensions.greasemonkey.stats.lastsubmittime", "Thu, 01 Jan 1970 00:00:00 GMT");
pref("extensions.greasemonkey.stats.optedin", false);
pref("extensions.greasemonkey.stats.prompted", false);
pref("extensions.greasemonkey.stats.url", "https://stats.greasespot.net/submit/");
pref("extensions.greasemonkey.sync.enabled", true);
pref("extensions.greasemonkey.sync.values", false);
pref("extensions.greasemonkey.sync.values_max_size_per_script", 65536);
pref("extensions.greasemonkey.unmhtIsGreaseable", false);
pref("extensions.greasemonkey.version", "0.0");
pref("services.sync.prefs.sync.extensions.greasemonkey.enableScriptRefreshing", true);
pref("services.sync.prefs.sync.extensions.greasemonkey.globalExcludes", true);
pref("services.sync.prefs.sync.extensions.greasemonkey.newScript.removeUnused", true);
pref("services.sync.prefs.sync.extensions.greasemonkey.newScript.template", true);
pref("services.sync.prefs.sync.extensions.greasemonkey.requireSecureUpdates", true);
pref("services.sync.prefs.sync.extensions.greasemonkey.showGrantsWarning", true);
pref("services.sync.prefs.sync.extensions.greasemonkey.stats.optedin", true);
pref("services.sync.prefs.sync.extensions.greasemonkey.stats.lastsubmittime", true);
pref("services.sync.prefs.sync.extensions.greasemonkey.sync.enabled", true);
pref("services.sync.prefs.sync.extensions.greasemonkey.sync.values", true);
