#include "nsISupports.idl"
#include "nsIDOMDocument.idl"

[scriptable, uuid(f0e15a10-1cc0-11da-8cd6-0800200c9a66)]
interface gmIMenuCommand : nsISupports
{
  [readonly] attribute AString name;
  [readonly] attribute AString accelKey;
  [readonly] attribute AString accelModifiers;
  [readonly] attribute AString accessKey;
  [readonly] attribute nsIDOMWindow window;

  void doCommand();
};
