// ==UserScript==
// @name Data URL Icon
// @description The `data:` scheme works for `@icon`.
// @icon data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEAAAABAAQMAAACQp+OdAAAABlBMVEUAAAD///+l2Z/dAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH4QkZEgM1U/H4HQAAABl0RVh0Q29tbWVudABDcmVhdGVkIHdpdGggR0lNUFeBDhcAAACPSURBVCjPrdKxDYAwDATARykoMwKjMBqMllEYISUFwtix9C6CEEi4iK5L8m+ISM16QOQEloYK5IYCpAboGA7DrNgNk6IasmIzjIpiSIrVMCjQRnA6FhyOGbtjClRHDmyOMVAc6QarY3iFv+bTpQ+P73/ap9EnxjAZLwOPClgKa2JxrJLlsu5YAK4El8TX5gJnC3YtvN3fyAAAAABJRU5ErkJggg==
// ==/UserScript==

