// ==UserScript==
// @name        Many include/exclude test.
// @description This script specifies so many `@include`s and `@exclude`s that it will force the install dialog to scroll.
// @grant       none
// @include     http://example.org/a
// @exclude     http://example.org/a/a
// @include     http://example.org/a
// @exclude     http://example.org/a/b
// @include     http://example.org/a
// @exclude     http://example.org/a/c
// @include     http://example.org/a
// @exclude     http://example.org/a/d
// @include     http://example.org/a
// @exclude     http://example.org/a/e
// @include     http://example.org/a
// @exclude     http://example.org/a/f
// @include     http://example.org/a
// @exclude     http://example.org/a/g
// @include     http://example.org/b
// @exclude     http://example.org/b/a
// @include     http://example.org/b
// @exclude     http://example.org/b/b
// @include     http://example.org/b
// @exclude     http://example.org/b/c
// @include     http://example.org/b
// @exclude     http://example.org/b/d
// @include     http://example.org/b
// @exclude     http://example.org/b/e
// @include     http://example.org/b
// @exclude     http://example.org/b/f
// @include     http://example.org/b
// @exclude     http://example.org/b/g
// @include     http://example.org/c
// @exclude     http://example.org/c/a
// @include     http://example.org/c
// @exclude     http://example.org/c/b
// @include     http://example.org/c
// @exclude     http://example.org/c/c
// @include     http://example.org/c
// @exclude     http://example.org/c/d
// @include     http://example.org/c
// @exclude     http://example.org/c/e
// @include     http://example.org/c
// @exclude     http://example.org/c/f
// @include     http://example.org/c
// @exclude     http://example.org/c/g
// @include     http://example.org/d
// @exclude     http://example.org/d/a
// @include     http://example.org/d
// @exclude     http://example.org/d/b
// @include     http://example.org/d
// @exclude     http://example.org/d/c
// @include     http://example.org/d
// @exclude     http://example.org/d/d
// @include     http://example.org/d
// @exclude     http://example.org/d/e
// @include     http://example.org/d
// @exclude     http://example.org/d/f
// @include     http://example.org/d
// @exclude     http://example.org/d/g
// @include     http://example.org/e
// @exclude     http://example.org/e/a
// @include     http://example.org/e
// @exclude     http://example.org/e/b
// @include     http://example.org/e
// @exclude     http://example.org/e/c
// @include     http://example.org/e
// @exclude     http://example.org/e/d
// @include     http://example.org/e
// @exclude     http://example.org/e/e
// @include     http://example.org/e
// @exclude     http://example.org/e/f
// @include     http://example.org/e
// @exclude     http://example.org/e/g
// @include     http://example.org/f
// @exclude     http://example.org/f/a
// @include     http://example.org/f
// @exclude     http://example.org/f/b
// @include     http://example.org/f
// @exclude     http://example.org/f/c
// @include     http://example.org/f
// @exclude     http://example.org/f/d
// @include     http://example.org/f
// @exclude     http://example.org/f/e
// @include     http://example.org/f
// @exclude     http://example.org/f/f
// @include     http://example.org/f
// @exclude     http://example.org/f/g
// @include     http://example.org/g
// @exclude     http://example.org/g/a
// @include     http://example.org/g
// @exclude     http://example.org/g/b
// @include     http://example.org/g
// @exclude     http://example.org/g/c
// @include     http://example.org/g
// @exclude     http://example.org/g/d
// @include     http://example.org/g
// @exclude     http://example.org/g/e
// @include     http://example.org/g
// @exclude     http://example.org/g/f
// @include     http://example.org/g
// @exclude     http://example.org/g/g
// ==/UserScript==
